/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Usuario;
import dao.UsuarioDAO;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jdelgado
 */
public final class AcompanhamentoUsuarioView extends javax.swing.JFrame {

    /**
     * Creates new form ViewJTable
     * @throws java.lang.Exception
     */
    public AcompanhamentoUsuarioView() throws Exception {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTUsuarios.getModel();
        jTUsuarios.setRowSorter(new TableRowSorter(modelo));

        readJTable();

    }

    public void readJTable() throws Exception {
        
        DefaultTableModel modelo = (DefaultTableModel) jTUsuarios.getModel();
        modelo.setNumRows(0);
      UsuarioDAO udao = new UsuarioDAO();

        for (Usuario u : udao.listarUsuarios()) {

            modelo.addRow(new Object[]{
                u.getId(),
                u.getNome(),
                u.getNivelAcesso(),
            });

        }

    }
    public void readJTableForDesc(String desc) throws Exception {
        
        DefaultTableModel modelo = (DefaultTableModel) jTUsuarios.getModel();
        modelo.setNumRows(0);
      UsuarioDAO udao = new UsuarioDAO();

        for (Usuario u : udao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
                u.getId(),
                u.getNome(),
                u.getNivelAcesso(),
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuarios = new javax.swing.JTable();
        txtBusca = new javax.swing.JTextField();
        ButtonBuscar = new javax.swing.JButton();
        ButtonExcluir = new javax.swing.JButton();
        LabelTitutlo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "NivelAcesso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTUsuariosMouseClicked(evt);
            }
        });
        jTUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTUsuariosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 158, 650, 480));

        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(txtBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 327, -1));

        ButtonBuscar.setText("Buscar");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 130, 40));

        ButtonExcluir.setText("Excluir");
        ButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 130, 40));

        LabelTitutlo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        LabelTitutlo.setText("Acompanhamento de Usuários");
        getContentPane().add(LabelTitutlo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 630, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTUsuariosMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTUsuariosMouseClicked

    private void jTUsuariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTUsuariosKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jTUsuariosKeyReleased

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        try {
            // TODO add your handling code here:

            readJTableForDesc(txtBusca.getText());
        } catch (Exception ex) {
            Logger.getLogger(AcompanhamentoUsuarioView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_ButtonBuscarActionPerformed



    private void ButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExcluirActionPerformed
        // TODO add your handling code here:

        //        System.out.println("Linha selecionada: "+jTUsuarios.getSelectedRow());
        if (jTUsuarios.getSelectedRow() != -1) {

          Usuario u = new Usuario();
          UsuarioDAO udao = new UsuarioDAO();

            u.setId((int) jTUsuarios.getValueAt(jTUsuarios.getSelectedRow(), 0));

            try {
                udao.delete(u);
            } catch (Exception ex) {
                Logger.getLogger(AcompanhamentoUsuarioView.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                readJTable();
            } catch (Exception ex) {
                Logger.getLogger(AcompanhamentoUsuarioView.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um para excluir.");
        }

    }//GEN-LAST:event_ButtonExcluirActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new AcompanhamentoUsuarioView().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(AcompanhamentoUsuarioView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonExcluir;
    private javax.swing.JLabel LabelTitutlo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTUsuarios;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
