/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Funcionario;
import dao.FuncionarioDAO;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jdelgado
 */
public final class CadastroFuncionarioView extends javax.swing.JFrame {

    /**
     * Creates new form ViewJTable
     * @throws java.lang.Exception
     */
    public CadastroFuncionarioView() throws Exception {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTFuncionarios.getModel();
        jTFuncionarios.setRowSorter(new TableRowSorter(modelo));

        readJTable();

    }

    public void readJTable() throws Exception {
        
        DefaultTableModel modelo = (DefaultTableModel) jTFuncionarios.getModel();
        modelo.setNumRows(0);
      FuncionarioDAO fdao = new FuncionarioDAO();

        for (Funcionario f : fdao.read()) {

            modelo.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getCargo(),
                f.getSalario()
            });

        }

    }
    public void readJTableForDesc(String desc) throws Exception {
        
        DefaultTableModel modelo = (DefaultTableModel) jTFuncionarios.getModel();
        modelo.setNumRows(0);
      FuncionarioDAO fdao = new FuncionarioDAO();

        for (Funcionario f : fdao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getCargo(),
                f.getSalario()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTFuncionarios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtfnome = new javax.swing.JTextField();
        LabelCargo = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        txtBuscaCargo = new javax.swing.JTextField();
        ButtonBuscar = new javax.swing.JButton();
        ButtonCadastrar = new javax.swing.JButton();
        ButtonExcluir = new javax.swing.JButton();
        ButtonAtualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Cargo", "Salario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuncionariosMouseClicked(evt);
            }
        });
        jTFuncionarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFuncionariosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTFuncionarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 358, 650, 280));

        jLabel3.setText("Salário");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, -1));

        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 213, 25));

        jLabel4.setText("Nome");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, -1));

        txtfnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtfnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 213, 25));

        LabelCargo.setText("Cargo");
        getContentPane().add(LabelCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 120, -1));
        getContentPane().add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 213, 25));
        getContentPane().add(txtBuscaCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 327, -1));

        ButtonBuscar.setText("Buscar");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 130, 40));

        ButtonCadastrar.setText("Cadastrar");
        ButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 130, 40));

        ButtonExcluir.setText("Excluir");
        ButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 130, 40));

        ButtonAtualizar.setText("Atualizar");
        ButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 130, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setText("Cadastro de Funcionarios");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 255, 590, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuncionariosMouseClicked
        // TODO add your handling code here:

        if (jTFuncionarios.getSelectedRow() != -1) {
            txtfnome.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 1).toString());
            txtCargo.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 2).toString());
            txtSalario.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 3).toString());

        }

    }//GEN-LAST:event_jTFuncionariosMouseClicked

    private void jTFuncionariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFuncionariosKeyReleased
        // TODO add your handling code here:

        if (jTFuncionarios.getSelectedRow() != -1) {

            txtfnome.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 1).toString());
            txtCargo.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 2).toString());
            txtSalario.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 3).toString());

        }

    }//GEN-LAST:event_jTFuncionariosKeyReleased

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        try {
            // TODO add your handling code here:

            readJTableForDesc(txtBuscaCargo.getText());
        } catch (Exception ex) {
            Logger.getLogger(CadastroFuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void txtfnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnomeActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void ButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAtualizarActionPerformed
        // TODO add your handling code here:

        if (jTFuncionarios.getSelectedRow() != -1) {

          Funcionario f = new Funcionario();
          FuncionarioDAO fdao = new FuncionarioDAO();

            f.setNome(txtfnome.getText());
            f.setCargo(txtCargo.getText());
            f.setSalario(Double.parseDouble(txtSalario.getText()));
            f.setId((int) jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 0));
            try {
                fdao.update(f);
            } catch (Exception ex) {
                Logger.getLogger(CadastroFuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
            }

            txtCargo.setText("");
            txtSalario.setText("");

            try {
                readJTable();
            } catch (Exception ex) {
                Logger.getLogger(CadastroFuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_ButtonAtualizarActionPerformed

    private void ButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExcluirActionPerformed
        // TODO add your handling code here:

        //        System.out.println("Linha selecionada: "+jTFuncionarios.getSelectedRow());
        if (jTFuncionarios.getSelectedRow() != -1) {

          Funcionario f = new Funcionario();
          FuncionarioDAO fdao = new FuncionarioDAO();

            f.setId((int) jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 0));

            try {
                fdao.delete(f);
            } catch (Exception ex) {
                Logger.getLogger(CadastroFuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
            }

            txtfnome.setText("");
            txtCargo.setText("");
            txtSalario.setText("");

            try {
                readJTable();
            } catch (Exception ex) {
                Logger.getLogger(CadastroFuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um para excluir.");
        }

    }//GEN-LAST:event_ButtonExcluirActionPerformed

    private void ButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarActionPerformed
        // TODO add your handling code here:

      Funcionario f = new Funcionario();
      FuncionarioDAO fdao = new FuncionarioDAO();

        f.setNome(txtfnome.getText());
        f.setCargo(txtCargo.getText());
        f.setSalario(Double.parseDouble(txtSalario.getText()));
        try {
            fdao.create(f);
        } catch (Exception ex) {
            Logger.getLogger(CadastroFuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtfnome.setText("");
        txtCargo.setText("");
        txtSalario.setText("");

        try {
            readJTable();

            //        DefaultTableModel dt = (DefaultTableModel) jTFuncionarios.getModel();
            //        Object[] dados = {txtDesc.getText(), txtQtd.getText(), txtSalario.getText()};
            //        dt.addRow(dados);
        } catch (Exception ex) {
            Logger.getLogger(CadastroFuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new CadastroFuncionarioView().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(CadastroFuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAtualizar;
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonCadastrar;
    private javax.swing.JButton ButtonExcluir;
    private javax.swing.JLabel LabelCargo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTFuncionarios;
    private javax.swing.JTextField txtBuscaCargo;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtfnome;
    // End of variables declaration//GEN-END:variables
}
