/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConnectionFactory;

import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jdelgado
 */
public final class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form ViewJTable
     * @param connection
     * @throws java.lang.Exception
     */

    

    public MenuView(Connection connection) throws Exception {
        this.connection = connection;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        LabelTitutlo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAcompanhamento = new javax.swing.JMenu();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuItemFuncionarios = new javax.swing.JMenuItem();
        jMenuItemProdutos = new javax.swing.JMenuItem();
        menuOperacoes = new javax.swing.JMenu();
        jMenuItemCaixa = new javax.swing.JMenuItem();
        jMenuItemCompra = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTitutlo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        LabelTitutlo.setText("Menu Administrador");
        getContentPane().add(LabelTitutlo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 650, 280));

        menuAcompanhamento.setText("Acompanhamento");

        jMenuItemUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemUsuarios.setText("Acompanhamento Usuários");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                 try {
                    AcompanhamentoUsuarioView usuarioView = new AcompanhamentoUsuarioView();
                    usuarioView.setVisible(true);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        menuAcompanhamento.add(jMenuItemUsuarios);

        jMenuItemFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemFuncionarios.setText("Cadastro Funcionários");
        jMenuItemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    CadastroFuncionarioView funcionarioView = new CadastroFuncionarioView();
                    funcionarioView.setVisible(true);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                jMenuItemFuncionariosActionPerformed(evt);
            }
        });
        menuAcompanhamento.add(jMenuItemFuncionarios);

        jMenuItemProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemProdutos.setText("Cadastro Produtos");
        jMenuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                 try {
                    CadastroProdutoView produtoView = new CadastroProdutoView();
                    produtoView.setVisible(true);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                jMenuItemProdutosActionPerformed(evt);
            }
        });
        menuAcompanhamento.add(jMenuItemProdutos);

        jMenuBar1.add(menuAcompanhamento);

        menuOperacoes.setText("Operações");

        jMenuItemCaixa.setText("Caixa");
        jMenuItemCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                 try {
                    CaixaView caixaView = new CaixaView();
                    caixaView.setVisible(true);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                jMenuItemCaixaActionPerformed(evt);
            }
        });
        menuOperacoes.add(jMenuItemCaixa);

        jMenuItemCompra.setText("Compra");
        jMenuItemCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                 try {
                    CompraView compraView = new CompraView();
                    compraView.setVisible(true);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                jMenuItemCompraActionPerformed(evt);
            }
        });
        menuOperacoes.add(jMenuItemCompra);

        jMenuBar1.add(menuOperacoes);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTUsuariosMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTUsuariosMouseClicked

    private void jTUsuariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTUsuariosKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jTUsuariosKeyReleased

    private void jMenuItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionariosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItemFuncionariosActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jMenuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemProdutosActionPerformed

    private void jMenuItemCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCaixaActionPerformed

    private void jMenuItemCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCompraActionPerformed




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    Connection connection = ConnectionFactory.getConnection();

                    MenuView menuView = new MenuView(connection);
                    menuView.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        });
    }
    private final Connection connection;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTitutlo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCaixa;
    private javax.swing.JMenuItem jMenuItemCompra;
    private javax.swing.JMenuItem jMenuItemFuncionarios;
    private javax.swing.JMenuItem jMenuItemProdutos;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAcompanhamento;
    private javax.swing.JMenu menuOperacoes;
    // End of variables declaration//GEN-END:variables
}
